## Top 3 per research phase

- *Discovery* Acrobat Reader, Google Scholar, and Institutional Access are all used by approximately 500 respondents. Looking at the more detailed figures showing all tools per research activity, it becomes clear that these tools are not direct competitors: each are leading tools in different research activities. Acrobat Reader is a very poular tool for reading, Google Scholar for searching literature, and Institutional Access to gain access to academic literature.

- *Analysis* Excel is most widely used within the VU, with SPSS a close second, and R a more distant third. These tools fall within the same activity class, and could be considered rival tools. It is notable that very few reseachers use tools to share there analysis, and it would be interesting to see how this evolves in the future.

- *Writing* Microsoft Word is the most popular writing tool by far, and nearly all respondents indicate that they use Word. The second and third most popular tools in the Writing category are reference managers: Endnote and Mendeley. Endnote is supported by the Library, but Mendeley has only slightly fewer users.

- *Publication* Unsurprisingly, the traditional topical journal (ie, 'closed' access) is still the leading outlet for academic work; more than eighty per cent of respondents with at least one publication indicate they have published in such a journal. The second and third most popular tools, ResearchGate and Open Access topical journals, are Open Access outlets. Note that ResearchGate is seen as a tool for archival, rather than publication.

- *Outreach* Generally, outreach to other academics is more popular than outreach to a broader public. ResearchGate and Google Scholar profiles are the most popular tools in this category. Twitter, and to a lesser extent WordPress, are used as tools for outreach to a broader public. Very few researchers make their presentations available for others.

- *Assessment* In the assessment phase, researchers mostly use Thomson reuters' Web of Science Journal Citation Reports to measure impact. Scopus is used as well, but much less often, presumably because the VU does not offer access to it. Alternative ('open') ways of peer review have very few users.
<!-- WoS is supported by the UB? -->

```{r}
#Vraag131.top3.fasen.R

# WIN GRAPH DISABLED FOR KNITR COMPATIBILITY!
#win.graph(14,7)

par(mfrow=c(2,3))
for(i in 1:length(PhaseResearchCycle))
{
  ##PLOTS
  par(mar = c(5,8,4,2) +0.1)

  ColNames.Phase.i <- as.character(Tools[which(Tools[,"PhaseResearchCycle"]==i),"Variable.name"])
  ToolUse.Phase.i<- ToolUse.totaal[ColNames.Phase.i]
  ToolUse.Phase.i<- ToolUse.Phase.i[order(-ToolUse.Phase.i)]

  #set en wrap labels voor y-as
  labs <- Tools[match(as.character(names(ToolUse.Phase.i[1:3])),Tools[,"Variable.name"]),"Tool.name"]
  wr.lab <- wrap.labels(labs, 10)
  fill <- Tools[match(as.character(names(ToolUse.Phase.i[1:3])),Tools[,"Variable.name"]),"UB.support"]

  # plot gebruikers top 3 in horizontale bargraph
  barplot(ToolUse.Phase.i[1:3], main=PhaseResearchCycle[i],xlim=c(0,max(ToolUse.totaal)),
          xlab="Aantal gebruikers: Top 3 van alle respondenten\n(dichte arcering=UB support)",
          cex.names=0.7,cex.main=1,horiz=T,las=1,
          names.arg=wr.lab,col=Kleuren[i],density=((fill+1)^2)*20)
}
```
