As a quick summary we have made a table to show the one most used tool per research phase in each discipline.
A more detailed explanation is given in the section below the table, but for the one most used tool we can state the following:

- *Discovery:* Most disciplines use Google Scholar to discover new literature. Medicine use PubMeb as their primary source for search. One could say that Lifesciences find having campus access to literature more important than searching for that literature, but in the detail section below we see a more elaborate explanation, where their attention for search is spread between Google Scholar and PubMed.

- *Analysis:* MS Excel is the most popular tool for analysis in all disciplines, except for Medicine where they use SPSS.

- *Writing:* Here MS Word is the most popular tool for writing in all disciplines, except for Engineering&Technology where they use LaTeX.

- *Publication:* Pubishing in Traditional Topical journals is still by far the most popular publication method, despite of the high support for Open Access.

- *Outreach* ResearchGate is the most popular platform for profiling your research within the research community, except for two disciplines who use RG slightly less. Engineering&Technology use Google Scholar Citations a bit more, and Arts&Humanities use Academia.edu more.

- *Assessment* Physics, Medicine, Lifesciences and Law use Web of Science for assessment of their research, and the oter disciplines use the Journal Citation Register, which both contain the same impact factor calculated from journals in the ISI database. Internationally there is a lot of debate going on if the [merit of an article should count](http://www.nature.com/news/beat-it-impact-factor-publishing-elite-turns-against-controversial-metric-1.20224?WT.mc_id=TWT_NatureNews), and not the merit of the journal. Also discussed is the reward sysem to give [credit where credit is due](http://www.nature.com/news/publishing-credit-where-credit-is-due-1.15033).


```{r}
#Vraag211.top1.tabel.R

#construct matrix voor output meest gebruikte tool in tabelvorm
top1.discipline <- mat.or.vec(length(Disciplines), length(PhaseResearchCycle))
colnames(top1.discipline) <- PhaseResearchCycle
rownames(top1.discipline) <- Disciplines
#vul top1.discipline met meest gebruikte tool per discipline per researchphase

for(i in 1:length(PhaseResearchCycle))
{
  #select all tools from phase i
  ToolUse.Phase.i<-ToolUse.per.discipline[,as.character(Tools[which(Tools[,"PhaseResearchCycle"]==i),"Variable.name"])]
  for(j in 1:length(Disciplines))
  {
    #sorteer gebruik tools phase i in discipline j
    ToolUse.Phasei.Disciplinej<- ToolUse.Phase.i[j,order(-ToolUse.Phase.i[j,])]
    #zet naam meest gebruikte tool in top1.discipline cell [j,i]
    Name.Most.Used<- Tools[match(as.character(names(ToolUse.Phasei.Disciplinej[1])),Tools[,"Variable.name"]),"Tool.name"]
    top1.discipline[j,i]<- as.character(Name.Most.Used)
  }
}


colors <- matrix(Kleuren,nrow=length(Disciplines),ncol=length(PhaseResearchCycle))

# WIN GRAPH DISABLED FOR KNITR COMPATIBILITY!
#win.graph(14,7)

par(mar=c(0,0,1,0))
plot_table(top1.discipline, Kleuren, "gray",main="Most popular tool in a research phase for a discipline", text.cex=0.8)
```
