<!-- # VU&VUmc vs OECD countries -->

The 101 Innovations survey received responses from many different countries. This makes it possible to compare responses from VU & VUmc faculty with international averages. We limit the comparison to the 34 [OECD member states](http://www.oecd.org/about/membersandpartners/list-oecd-member-countries.htm) (checked 3 May 2016; note that the list also includes the Netherlands). Although this list comprises many different countries, responses from these  countries are more comparable to the VU than those from the complete list, and allow for a more meaningful comparison. For example, respondents from countries with low GDP often use Zotero (free of charge), while EndNote (paid) is used more in countries with a higher GDP.

In the subsections below, we discuss the different research phases in turn. In each of the figures, hatched bars represent responses from VU and VUmc staff, and filled bars represent all other respondents from OECD countries. All data is represented as the percentage of all respondents in that group. For example, in the graph for `Discovery_search` it is shown that about forty percent of all OECD respondents have indicated using PubMed for Search, and about fifty percent of all VU&VUmc staff.

Overall, differences between OECD and VU repondents are not very large, and it is difficult to discern structural deviations at the VU from the OECD averages. One thing that is noteworthy and of possible interest to the Library is that usage of Mendeley for discovery and reference management is higher at the VU than in other OECD countries, despite access to the Endnote application.

<!--
 - betere legenda maken;
 - axis-beschrijving kan veel korter;
 - y axis beter op (25-)50-(75-)100 %?
 - OECD=incl Nederland?
 - why are some graphs so much higher?
-->


```{r Vraag132.AlleTools.subfasen.Rmd, echo=FALSE,results='asis'}
#Vraag131.AlleTools.subfasen.R

d <- c("##Discovery
<<<<<<< 136d71d566ce87725aa94e5bb74c3f15a3fc2019
The triplets of VU and VUmc favourites---Acrobat Reader, Google Scholar, institutional access--- are popular in the OECD as well. For searching, PubMed and Mendeley are used more often by VU staff, while Scopus is used less (no surprise here, since the VU has no subscription at the time of the survey).",
"##Analysis
Use of SPSS as a tool for analysis is almost twice as large at the VU than for the OECD average.",
"##Writing
Mendeley users for reference management are strongly represented at the VU. The preference for Mendeley is at the expense of all other tools except Endnote. For writing, VU respondents are relatively traditional, with high usage of MS Word and low usage of Google Docs and LaTeX.",
"##Publication
Scopus usage is relatively low. Few VU respondents use the institutional repository for archival.",
"##Outreach
There are no clear differences between the VU or OECD averages. VU respondents seem to use more tools for outreach to the general public (mainly through Twitter, WordPress, and the Wikipedia), but differences are not substantial",

"##Assessment
...")

explanation.tekst <- c(paste(d,sep=''))

for(i in 1:length(PhaseResearchCycle))
{
  # plaats tekst in loops
  cat(explanation.tekst[i], "\n")

  # Print heading
  par(mar = c(6,6,4,1) +0.1)
  #selecteer SubPhases behoorden bij PhaseResearchCyclie[i]
  SubPhases.Phase.i<-SubPhases[grep(PhaseResearchCycle[i],SubPhases)]
  n.rows<-ceiling(length(SubPhases.Phase.i)/2)

  # WIN GRAPH DISABLED FOR KNITR COMPATIBILITY!
  #win.graph(14,n.rows*4)

  par(mfrow=c(n.rows,2))
  for(j in 1:length(SubPhases.Phase.i))
  {
    par(mar = c(6,6,4,1) +0.1)
    #selecteer kolommen/tools uit fase[i] van de research cycle
    ColNames.SubPhase.j <- as.character(Tools[which(Tools[,"SubPhase"]==SubPhases.Phase.i[j]),"Variable.name"])
    #selecteer tools van subphase j uit phase i in ToolUse.per.TenureStatus
    ToolUse.Subphase.j<-(ToolUse.OECDvsVU[,ColNames.SubPhase.j]/respondenten.OECDvsVU)*100

    #sort tools from ToolUse.Subphase.j by difference in tooluse in OECD-countries
    ToolUse.Subphase.j<-ToolUse.Subphase.j[,order(-ToolUse.Subphase.j[1,])]
    #define axis labels
    labs <- Tools[match(as.character(colnames(ToolUse.Subphase.j)),Tools[,"Variable.name"]),"Tool.name"]
    wr.lab <- wrap.labels(labs, 10)
    #plot
    barplot(ToolUse.Subphase.j,beside=TRUE,main=SubPhases.Phase.i[j],
      names.arg=wr.lab,las=3,cex.names=0.7,col=rep(Kleuren[i],2),density=c(1000,20),
      ylim=c(0,100),cex.lab=if(n.rows==1){0.8},
      ylab="[filled bars= OECD countries] \n [hatched bars = VU&VUmc] \n % tool users")
  }
  cat("\n")
  cat("\n")
}
```
