## Extremities: Tenures vs Non-tenures
The figure below shows only the tools with the biggest difference between tenures users and non-tenured researchers.

For the first set of graphs showing the two most pronounced differences, we calculate the difference by substracting the use in the tenured group from the use in the non-tenured group (both as percentages). The upper bars show the largest positive difference (ie, the tool is more popular among non-tenured researchers); the lower bars show the largest negative difference.

- **Discovery** The difference in use for PubMed and table of content announcements for journals stand out as the most significant discrepancies in the Discovery phase. Although not featuring in the 'top-2' figures, the use of Mendely stands out when inspecting the more detailed graphs: non-tenured (generally younger) researchers use Mendeley more often in the Reading, Searching and Alert activities within the Discovery phase.

- **Analysis** Tool use for analysis is stronger with non-tenured researchers across the board. This holds for relatively new (and more open) tools such as R and Python, as well as for long-standing software such as Excel and MATLAB. The large difference for SPSS is no outlier. Tools for sharing analysis scripts are not very popular, and tool usage is low overall. Somewhat unexpectedly, use of the Open Science Framework is stronger for the tenured then for the non-tenured group. This could have to do with the fact <!-- is it a fact? --> that the OSF is often used for grant applications, and that this arguably is a more important activity for tenured researchers.

- **Writing** The importance of Mendeley in the research workflow of non-tenured researchers is again apparent in the Writing Phase. Among this group, Mendeley is the most popular reference management software, more popular than Endnote---the most popular reference tool for tenured researchers. For the writing itself, MS Word is by far the most popular tool among both groups.

- **Publication** <!-- Should we make these graphs relative to the number of people that have published? Difficult to interpret now --> In general, tenured researchers use more tools in the Publication phase; probably they simply publish more. This makes it difficult to interpret these figures properly. A few tools stand out. First, PubMed is relatively popular for archival of publications for non-tenured researchers, although in absolute terms ResearchGate is the most popular repository for both groups. GitHub is used mostly by non-tenured researchers as a repository for scripts and software code.

- **Outreach** Tenured researchers seem to spend more effort on their research profile, as tool use in this phase is higher for that group. ResearchGate is popular among both groups. Although to a lesser extent (differences are less pronounced), tenured researchers also use more tools for outrecach to a broader public.

- **Assessment** The difference is use of Web of Science indicators for impact assessment is striking: about 55% of tenured researchers indicate using the tool, versus appraximately 20% of non-tenured reseachers. Altmetrics and the PLoS metrics are not very popular (yet) in comparison, and are used by both groups, although slightly more by non-tenured researchers.
Tools to the **left** of each graph are used more by the **Tenured** group.
Tools to the **right** of each graph are used more by the **Non-Tenured** group.

```{r Vraag111.top2.fasen.Rmd, echo=FALSE}

# Vraag111.top2.fasen.R
#---- PlotTop2Fasen ----

#Plot grafieken met gebruik door tenured en non-tenured gebruikers voor top 2 tools in (totaal) gebruik per fase van de research cycle

#prepare layout panel of graphs

# WIN GRAPH DISABLED FOR KNITR COMPATIBILITY!
#win.graph(15,8)

par(mfrow=c(2,3))
par(mar = c(4,4,3,1) +0.1)
#Plot figuur met overal top 2 voor elke fase van de research cycle
for(i in 1:length(PhaseResearchCycle))
{
  #selecteer kolommen/tools uit fase[i] van de research cycle
  ColNames.Phase.i <- as.character(Tools[which(Tools[,"PhaseResearchCycle"]==i),"Variable.name"])
  #
  PhaseResearchCycle.i<-ToolUse.per.TenureStatus[,ColNames.Phase.i]

  #selecteer de tool met het grootste negatieve verschil tussen de tenure groepen
  Tool.min.difference<-PhaseResearchCycle.i[,which(PhaseResearchCycle.i[3,]==min(PhaseResearchCycle.i[3,]))]
  Name.Tool.min.difference<-names(which(PhaseResearchCycle.i[3,]==min(PhaseResearchCycle.i[3,])))
  #selecteer de tool met het grootste positieve verschil tussen de tenure groepen
  Tool.max.difference<-PhaseResearchCycle.i[,which(PhaseResearchCycle.i[3,]==max(PhaseResearchCycle.i[3,]))]
  Name.Tool.max.difference<-names(which(PhaseResearchCycle.i[3,]==max(PhaseResearchCycle.i[3,])))
  #zet data van tools met grootste verschil in 1 matrix
  Extreme.differences<- cbind(Tool.min.difference,Tool.max.difference)
  #geef kolommen de juiste toolnaam
  colnames(Extreme.differences) <- c(Name.Tool.min.difference,Name.Tool.max.difference)

  #set en wrap labels voor y-as
  labs <- Tools[match(as.character(colnames(Extreme.differences)),Tools[,"Variable.name"]),"Tool.name"]
  wr.lab <- wrap.labels(labs, 10)

  #plot data Extreme.differences en gebruik hierboven gedefinieerde labelnamen
  barplot(Extreme.differences[1:2,],beside=TRUE,horiz=T,main=PhaseResearchCycle[i],
    names.arg=wr.lab,las=1,cex.names=0.7,col=rep(Kleuren[i],2),density=c(20,1000),
    xlim=c(0,max(ToolUse.per.TenureStatus[1:2,])),
    xlab="% tool users [filled bars: tenured] \n [hatched bars: non-tenured]")
}
```
